import { Poppins } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import 'bootstrap/dist/css/bootstrap.min.css';
// import { ThemeProvider } from "react-bootstrap";


const inter = Poppins({ subsets: ["latin"], weight:['400', '500', '600', '700', '800'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

{/* <ThemeProvider
  breakpoints={['xxxl', 'xxl', 'xl', 'lg', 'md', 'sm', 'xs', 'xxs']}
  minBreakpoint="xxs"
></ThemeProvider> */}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
